# Generated by Django 6.0.1 on 2026-02-10 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(db_column='complaint_id', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Roads', 'Roads'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Traffic', 'Traffic'), ('Pollution', 'Pollution'), ('Others', 'Others')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, db_column='image_url', null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('admin_comment', models.TextField(blank=True, db_column='admin_notes', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('upvoters', models.ManyToManyField(blank=True, db_table='complaint_upvotes', related_name='upvoted_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='notification_id', primary_key=True, serialize=False)),
                ('message', models.TextField(db_column='message_text')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(db_column='linked_complaint_id', on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
                ('user', models.ForeignKey(db_column='target_citizen_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
